export class BuildingLicense{

    constructor(
        public id: number = null,
        public Working_Area: number =null,
        public P_North: string =null,
        public P_South: string =null,
        public P_East: string =null,
        public P_West: string =null,
        public North_RODOD: string =null,
        public South_RODOD: string =null,
        public East_RODOD: string =null,
        public West_RODOD: string =null,
        public North_length: string =null,
        public South_Length: string =null,
        public East_length: string =null,
        public West_length: string =null,
        public D_North: string =null,
        public D_South: string =null,
        public D_East: string =null,
        public D_West: string =null,
        public Work_Description: string =null,
        public Request_Description: string =null,
        public Certificate_id: number =null,
        public ENG_Office_ID: number =null,
        public Request_Eng_id: number =null,
        public Work_Category: string =null,
        public Units_Number: number =null,
        public License_Type: string =null,
        public Buliding_Type_id: string =null,
        public Repeated_Number: number =null,
        public Land_Area: number =null,
    ){}
}