
import { Fee } from './fee';

export const MOCK_FEES=[
	// new Fee("Fee one"),
	// new Fee("Fee two"),
	// new Fee("Fee three"),
	// new Fee("Fee four"),
	// new Fee("Fee five"),
	// new Fee("Fee six"),
	// new Fee("Fee seven"),
	// new Fee("Fee eight"),
	// new Fee("Fee nine"),
	// new Fee("Fee ten"),
	// new Fee("Fee eleven"),
	// new Fee("Fee twelve"),
	// new Fee("Fee thirteen"),
	// new Fee("Fee fourteen"),
	// new Fee("Fee fifteen"),
	// new Fee("Fee sixteen"),
	// new Fee("Fee seventeen"),
	// new Fee("Fee eighteen"),
	// new Fee("Fee nineteen"),
	// new Fee("Fee twenty"),
	// new Fee("Fee twenty one"),
	// new Fee("Fee twenty two"),
	// new Fee("Fee twenty three"),
	// new Fee("Fee twenty four"),
	// new Fee("Fee twenty five"),
	// new Fee("Fee twenty six"),
];