
import { Document } from './document';

export const MOCK_DOCUMENTS=[
	// new Document("document one"),
	// new Document("document two"),
	// new Document("document three"),
	// new Document("document four"),
	// new Document("document five"),
	// new Document("document six"),
	// new Document("document seven"),
	// new Document("document eight"),
	// new Document("document nine"),
	// new Document("document ten"),
	// new Document("document eleven"),
	// new Document("document twelve"),
	// new Document("document thirteen"),
	// new Document("document fourteen"),
	// new Document("document fifteen"),
	// new Document("document sixteen"),
	// new Document("document seventeen"),
	// new Document("document eighteen"),
	// new Document("document nineteen"),
	// new Document("document twenty"),
	// new Document("document twenty one"),
	// new Document("document twenty two"),
	// new Document("document twenty three"),
	// new Document("document twenty four"),
	// new Document("document twenty five"),
	// new Document("document twenty six"),
];